### ISSUE TITLE
Supplied javaHome is not a valid folder

### ISSUE THREAD

**Issue by ec-c** [clojurephant/clojurephant-tooling#3]
When I run `(do (require '[dev.clojurephant.tooling.figwheel-main :as fig]) (fig/start :dev))` in a REPL, I get the following error:

> Execution error (IllegalArgumentException) at org.gradle.tooling.internal.consumer.parameters.ConsumerOperationParameters/validateJavaHome (ConsumerOperationParameters.java:287).
> Supplied javaHome is not a valid folder. You supplied: \usr\lib\jvm\java-18-openjdk-amd64

I assume the problem are these JVM hard links:
https://github.com/clojurephant/clojurephant-tooling/blob/d0d08a2a450184406354e74a653bd1b5270ce15b/src/main/clojure/dev/clojurephant/tooling/core.clj#L61

https://github.com/clojurephant/clojurephant-tooling/blob/d0d08a2a450184406354e74a653bd1b5270ce15b/src/main/clojure/dev/clojurephant/tooling/core.clj#L111

**Comment by ajoberstar** [comment]
Ah, yep that shouldn't be hard coded there. Will have to fix that.
